# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f4017b2a495ab98b81f9a81a4509ab5690504badebb0b002c873dd8aaf51a9da073608373263384d2a9cac13dc69d841f44863a771de50af5fcbb84e2c59ab69

test:
  secret_key_base: 1cd4c59cce71fe6669564147a1e7b94991e166e38e1e941456b53890ce88f47db425a0df38ca547ae2266b71c50126be1da602444d77c8b7e225659d19fd99cd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
